"""Research Report Generator.

Generates professional HTML research reports from aggregated agent outputs.
Styled to resemble institutional equity research reports.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from src.config.logging_config import get_logger

logger = get_logger("report_generator")


def generate_html_report(report_data: dict, output_path: str | None = None) -> str:
    """Generate a professional HTML research report.

    Args:
        report_data: Aggregated report dict from aggregator.
        output_path: Optional file path to write HTML.

    Returns:
        HTML string.
    """
    symbol = report_data.get("symbol", "UNKNOWN")
    recommendation = report_data.get("recommendation", "Hold")
    conviction = report_data.get("conviction", "medium")
    composite = report_data.get("composite_score", 50)
    generated_at = datetime.now().strftime("%B %d, %Y %H:%M")

    # Build sections
    exec_summary = report_data.get("executive_summary", "")
    if not exec_summary:
        exec_summary = _auto_executive_summary(report_data)

    earnings_section = _build_earnings_section(report_data.get("earnings_analysis"))
    macro_section = _build_macro_section(report_data.get("macro_assessment"))
    news_section = _build_news_section(report_data.get("news_sentiment"))
    quant_section = _build_quant_section(report_data.get("quant_signals"))
    peer_section = _build_peer_section(report_data.get("peer_comparison"))
    risk_section = _build_risk_section(report_data)
    source_section = _build_source_section(report_data)

    # Recommendation color
    rec_colors = {
        "Strong Buy": "#00873c",
        "Buy": "#4caf50",
        "Hold": "#ff9800",
        "Sell": "#f44336",
        "Strong Sell": "#b71c1c",
    }
    rec_color = rec_colors.get(recommendation, "#666")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FinSight Research Report – {symbol}</title>
<style>
{_get_css()}
</style>
</head>
<body>
<div class="report">

<!-- Header -->
<header class="report-header">
  <div class="header-left">
    <div class="logo">FinSight</div>
    <div class="subtitle">AI-Powered Equity Research</div>
  </div>
  <div class="header-right">
    <div class="report-date">{generated_at}</div>
  </div>
</header>

<!-- Title Bar -->
<div class="title-bar">
  <div class="symbol-name">
    <h1>{symbol}</h1>
    <span class="company-name">{report_data.get('company_name', '')}</span>
  </div>
  <div class="recommendation-box" style="background:{rec_color}">
    <div class="rec-label">Recommendation</div>
    <div class="rec-value">{recommendation}</div>
    <div class="rec-conviction">Conviction: {conviction.upper()}</div>
  </div>
</div>

<!-- Score Cards -->
<div class="score-cards">
  <div class="score-card">
    <div class="score-label">Composite</div>
    <div class="score-value">{composite:.0f}</div>
    <div class="score-bar"><div class="score-fill" style="width:{composite}%"></div></div>
  </div>
  {_score_card("Fundamental", report_data.get("fundamental_score"))}
  {_score_card("Quant", report_data.get("quant_score"))}
  {_score_card("Sentiment", report_data.get("sentiment_score"))}
  {_score_card("Macro", report_data.get("macro_score"))}
  {_score_card("Peer", report_data.get("peer_score"))}
</div>

<!-- Executive Summary -->
<section class="section">
  <h2>Executive Summary</h2>
  <p>{exec_summary}</p>
</section>

<!-- Bull / Bear Case -->
<div class="two-column">
  <div class="column bull-case">
    <h3>Bull Case</h3>
    <ul>{''.join(f'<li>{p}</li>' for p in report_data.get('bull_case', []))}</ul>
  </div>
  <div class="column bear-case">
    <h3>Bear Case</h3>
    <ul>{''.join(f'<li>{p}</li>' for p in report_data.get('bear_case', []))}</ul>
  </div>
</div>

<!-- Conflicts -->
{_build_conflicts_section(report_data.get('conflicts', []))}

<!-- Financial Analysis -->
{earnings_section}

<!-- Quantitative Signals -->
{quant_section}

<!-- Peer Comparison -->
{peer_section}

<!-- Macro Environment -->
{macro_section}

<!-- News & Sentiment -->
{news_section}

<!-- Risk Factors -->
{risk_section}

<!-- Regime Context -->
{_build_regime_section(report_data)}

<!-- Sources -->
{source_section}

<!-- Footer -->
<footer class="report-footer">
  <p>Generated by FinSight AI Research Platform. This report is for informational
  purposes only and does not constitute investment advice. Past performance is not
  indicative of future results.</p>
  <p class="footer-meta">Agents used: {', '.join(report_data.get('agents_used', []))}</p>
</footer>

</div>
</body>
</html>"""

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8")
        logger.info("report_written", path=output_path, symbol=symbol)

    return html


def _get_css() -> str:
    """Return CSS styles for the report."""
    return """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
       background: #f5f5f5; color: #333; line-height: 1.6; }
.report { max-width: 1000px; margin: 0 auto; background: #fff;
          box-shadow: 0 0 20px rgba(0,0,0,0.1); }

/* Header */
.report-header { display: flex; justify-content: space-between; align-items: center;
                  padding: 20px 40px; background: #1a237e; color: #fff; }
.logo { font-size: 24px; font-weight: bold; letter-spacing: 2px; }
.subtitle { font-size: 12px; opacity: 0.8; }
.report-date { font-size: 13px; opacity: 0.9; }

/* Title Bar */
.title-bar { display: flex; justify-content: space-between; align-items: center;
             padding: 25px 40px; border-bottom: 3px solid #1a237e; }
.symbol-name h1 { font-size: 36px; color: #1a237e; margin-bottom: 2px; }
.company-name { font-size: 16px; color: #666; }
.recommendation-box { color: #fff; padding: 15px 25px; border-radius: 8px;
                       text-align: center; min-width: 160px; }
.rec-label { font-size: 11px; text-transform: uppercase; opacity: 0.9; }
.rec-value { font-size: 22px; font-weight: bold; margin: 2px 0; }
.rec-conviction { font-size: 11px; opacity: 0.85; }

/* Score Cards */
.score-cards { display: flex; gap: 12px; padding: 20px 40px; flex-wrap: wrap; }
.score-card { flex: 1; min-width: 120px; background: #fafafa; border: 1px solid #e0e0e0;
              border-radius: 6px; padding: 12px; text-align: center; }
.score-label { font-size: 11px; text-transform: uppercase; color: #888; }
.score-value { font-size: 28px; font-weight: bold; color: #1a237e; }
.score-bar { height: 4px; background: #e0e0e0; border-radius: 2px; margin-top: 6px; }
.score-fill { height: 100%; background: #1a237e; border-radius: 2px; }
.score-na { font-size: 20px; color: #bbb; }

/* Sections */
.section { padding: 25px 40px; border-bottom: 1px solid #eee; }
.section h2 { font-size: 18px; color: #1a237e; margin-bottom: 12px;
              border-bottom: 2px solid #e3f2fd; padding-bottom: 6px; }
.section h3 { font-size: 15px; color: #333; margin: 12px 0 6px 0; }
.section p { margin-bottom: 8px; }
.section ul { margin-left: 20px; margin-bottom: 8px; }
.section li { margin-bottom: 4px; }
.metric-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
.metric { padding: 8px; background: #f9f9f9; border-radius: 4px; }
.metric-label { font-size: 11px; color: #888; }
.metric-value { font-size: 16px; font-weight: 600; }

/* Two Column */
.two-column { display: flex; gap: 20px; padding: 20px 40px; border-bottom: 1px solid #eee; }
.column { flex: 1; padding: 15px; border-radius: 6px; }
.bull-case { background: #e8f5e9; border: 1px solid #c8e6c9; }
.bear-case { background: #ffebee; border: 1px solid #ffcdd2; }
.bull-case h3 { color: #2e7d32; }
.bear-case h3 { color: #c62828; }

/* Conflicts */
.conflict-box { background: #fff3e0; border: 1px solid #ffe0b2; border-radius: 6px;
                padding: 12px; margin: 8px 0; }
.conflict-agents { font-weight: 600; color: #e65100; }

/* Table */
table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 13px; }
th, td { padding: 8px 12px; border: 1px solid #e0e0e0; text-align: left; }
th { background: #f5f5f5; font-weight: 600; color: #555; }
tr:nth-child(even) { background: #fafafa; }

/* Footer */
.report-footer { padding: 20px 40px; background: #f5f5f5; font-size: 11px; color: #888;
                  border-top: 1px solid #e0e0e0; }
.footer-meta { margin-top: 6px; }
"""


def _score_card(label: str, value: float | None) -> str:
    """Generate a single score card HTML."""
    if value is None:
        return f"""<div class="score-card">
    <div class="score-label">{label}</div>
    <div class="score-na">N/A</div>
    <div class="score-bar"><div class="score-fill" style="width:0%"></div></div>
  </div>"""
    return f"""<div class="score-card">
    <div class="score-label">{label}</div>
    <div class="score-value">{value:.0f}</div>
    <div class="score-bar"><div class="score-fill" style="width:{value}%"></div></div>
  </div>"""


def _auto_executive_summary(report_data: dict) -> str:
    """Auto-generate executive summary from available data."""
    symbol = report_data.get("symbol", "")
    rec = report_data.get("recommendation", "Hold")
    composite = report_data.get("composite_score", 50)

    parts = [f"We rate {symbol} as <strong>{rec}</strong> with a composite score of {composite:.0f}/100."]

    earnings = report_data.get("earnings_analysis", {})
    if earnings and not earnings.get("error"):
        thesis = earnings.get("investment_thesis", "")
        if thesis:
            parts.append(thesis[:300])

    macro = report_data.get("macro_assessment", {})
    if macro and not macro.get("error"):
        outlook = macro.get("equity_outlook", "")
        if outlook:
            parts.append(f"The macro environment outlook is {outlook}.")

    news = report_data.get("news_sentiment", {})
    if news and not news.get("error"):
        sentiment = news.get("sentiment_label", "")
        if sentiment:
            parts.append(f"News sentiment is {sentiment}.")

    return " ".join(parts)


def _build_earnings_section(data: dict | None) -> str:
    """Build Financial Analysis section from earnings agent output."""
    if not data or data.get("error"):
        return '<section class="section"><h2>Financial Analysis</h2><p>Not available.</p></section>'

    metrics_html = '<div class="metric-grid">'
    metrics = [
        ("Revenue Trend", data.get("revenue_trend", "N/A")),
        ("Revenue Growth YoY", _fmt_pct(data.get("revenue_growth_yoy"))),
        ("Gross Margin", _fmt_pct(data.get("gross_margin"))),
        ("Operating Margin", _fmt_pct(data.get("operating_margin"))),
        ("Net Margin", _fmt_pct(data.get("net_margin"))),
        ("FCF Yield", _fmt_pct(data.get("fcf_yield"))),
        ("D/E Ratio", _fmt_num(data.get("debt_to_equity"))),
        ("Current Ratio", _fmt_num(data.get("current_ratio"))),
        ("Balance Sheet", data.get("balance_sheet_quality", "N/A")),
    ]
    for label, value in metrics:
        metrics_html += f'<div class="metric"><div class="metric-label">{label}</div><div class="metric-value">{value}</div></div>'
    metrics_html += '</div>'

    guidance = ''.join(f'<li>{g}</li>' for g in data.get("key_guidance_points", []))
    thesis = data.get("investment_thesis", "")
    score = data.get("fundamental_score", "N/A")

    return f"""<section class="section">
  <h2>Financial Analysis</h2>
  <p><strong>Fundamental Score: {score}/100</strong> | Tone: {data.get('management_tone', 'N/A')}</p>
  {metrics_html}
  <h3>Investment Thesis</h3>
  <p>{thesis}</p>
  <h3>Key Guidance Points</h3>
  <ul>{guidance}</ul>
</section>"""


def _build_macro_section(data: dict | None) -> str:
    """Build Macro Environment section."""
    if not data or data.get("error"):
        return '<section class="section"><h2>Macro Environment</h2><p>Not available.</p></section>'

    return f"""<section class="section">
  <h2>Macro Environment</h2>
  <div class="metric-grid">
    <div class="metric"><div class="metric-label">Cycle Phase</div><div class="metric-value">{data.get('cycle_phase', 'N/A')}</div></div>
    <div class="metric"><div class="metric-label">GDP Trend</div><div class="metric-value">{data.get('gdp_growth_trend', 'N/A')}</div></div>
    <div class="metric"><div class="metric-label">Inflation</div><div class="metric-value">{data.get('inflation_trend', 'N/A')}</div></div>
    <div class="metric"><div class="metric-label">Fed Stance</div><div class="metric-value">{data.get('fed_policy_stance', 'N/A')}</div></div>
    <div class="metric"><div class="metric-label">Rate Direction</div><div class="metric-value">{data.get('rate_direction', 'N/A')}</div></div>
    <div class="metric"><div class="metric-label">Equity Outlook</div><div class="metric-value">{data.get('equity_outlook', 'N/A')}</div></div>
  </div>
  <h3>Sector Preferences</h3>
  <p>{', '.join(data.get('sector_preferences', []))}</p>
  <h3>Assessment</h3>
  <p>{data.get('reasoning', '')}</p>
</section>"""


def _build_news_section(data: dict | None) -> str:
    """Build News & Sentiment section."""
    if not data or data.get("error"):
        return '<section class="section"><h2>News & Sentiment</h2><p>Not available.</p></section>'

    articles_html = ""
    for a in data.get("notable_articles", [])[:5]:
        score = a.get("sentiment_score", 0)
        color = "#4caf50" if score > 0.2 else "#f44336" if score < -0.2 else "#ff9800"
        articles_html += f"""<tr>
      <td>{a.get('title', 'N/A')}</td>
      <td>{a.get('source', 'N/A')}</td>
      <td style="color:{color};font-weight:600">{score:+.2f}</td>
    </tr>"""

    themes = ', '.join(data.get("key_themes", []))

    return f"""<section class="section">
  <h2>News & Sentiment</h2>
  <p><strong>Overall: {data.get('sentiment_label', 'N/A')}</strong>
     (score: {data.get('overall_sentiment', 0):+.2f}) |
     Trend: {data.get('sentiment_trend', 'N/A')} |
     Articles: {data.get('articles_analyzed', 0)}</p>
  <h3>Key Themes</h3>
  <p>{themes}</p>
  <h3>Notable Articles</h3>
  <table><thead><tr><th>Title</th><th>Source</th><th>Sentiment</th></tr></thead>
  <tbody>{articles_html}</tbody></table>
  <h3>Market Impact</h3>
  <p>{data.get('market_impact_assessment', '')}</p>
</section>"""


def _build_quant_section(data: dict | None) -> str:
    """Build Quantitative Signals section."""
    if not data or data.get("error"):
        return '<section class="section"><h2>Quantitative Signals</h2><p>Not available.</p></section>'

    factors_html = ""
    for f in data.get("factor_scores", []):
        z = f.get("z_score", 0)
        color = "#4caf50" if z > 0.5 else "#f44336" if z < -0.5 else "#333"
        factors_html += f"""<tr>
      <td>{f.get('factor_name', '')}</td>
      <td style="color:{color}">{z:+.2f}</td>
      <td>{f.get('percentile', 50):.0f}%</td>
    </tr>"""

    return f"""<section class="section">
  <h2>Quantitative Signals</h2>
  <p><strong>Signal: {data.get('signal_direction', 'neutral').replace('_', ' ').title()}</strong>
     (strength: {data.get('signal_strength', 0):.2f}) |
     Composite: {data.get('composite_score', 0):.2f} |
     Percentile: {data.get('composite_percentile', 50):.0f}%</p>
  <h3>Factor Breakdown</h3>
  <table><thead><tr><th>Factor</th><th>Z-Score</th><th>Percentile</th></tr></thead>
  <tbody>{factors_html}</tbody></table>
  <p><strong>Strongest:</strong> {', '.join(data.get('strongest_factors', []))}</p>
  <p><strong>Weakest:</strong> {', '.join(data.get('weakest_factors', []))}</p>
</section>"""


def _build_peer_section(data: dict | None) -> str:
    """Build Peer Comparison section."""
    if not data or data.get("error"):
        return '<section class="section"><h2>Industry & Peers</h2><p>Not available.</p></section>'

    peers_html = ""
    for p in data.get("peers", [])[:8]:
        peers_html += f"""<tr>
      <td>{p.get('symbol', '')}</td>
      <td>{_fmt_num(p.get('pe_ratio'))}</td>
      <td>{_fmt_num(p.get('pb_ratio'))}</td>
      <td>{_fmt_pct(p.get('roe'))}</td>
      <td>{_fmt_pct(p.get('revenue_growth_yoy'))}</td>
    </tr>"""

    return f"""<section class="section">
  <h2>Industry & Peers</h2>
  <p>Sector: {data.get('sector', 'N/A')} | Peers: {data.get('peer_count', 0)} |
     Valuation: {data.get('pe_vs_peers', 'N/A')} vs peers</p>
  <table><thead><tr><th>Symbol</th><th>P/E</th><th>P/B</th><th>ROE</th><th>Rev Growth</th></tr></thead>
  <tbody>{peers_html}</tbody></table>
  <p><strong>Profitability Rank:</strong> #{data.get('profitability_rank', 'N/A')} |
     <strong>Growth Rank:</strong> #{data.get('growth_rank', 'N/A')}</p>
  <p>{data.get('peer_comparison_summary', '')}</p>
</section>"""


def _build_risk_section(report_data: dict) -> str:
    """Build Risk Factors section."""
    risks = report_data.get("key_risks", [])
    catalysts = report_data.get("catalysts", [])

    risks_html = ''.join(f'<li>{r}</li>' for r in risks)
    catalysts_html = ''.join(f'<li>{c}</li>' for c in catalysts)

    return f"""<section class="section">
  <h2>Risk Factors & Catalysts</h2>
  <div class="two-column" style="padding:0;border:none">
    <div class="column" style="background:#fff3e0;border:1px solid #ffe0b2">
      <h3>Key Risks</h3>
      <ul>{risks_html}</ul>
    </div>
    <div class="column" style="background:#e8f5e9;border:1px solid #c8e6c9">
      <h3>Catalysts</h3>
      <ul>{catalysts_html}</ul>
    </div>
  </div>
</section>"""


def _build_regime_section(report_data: dict) -> str:
    """Build Market Regime section."""
    regime = report_data.get("market_regime", "")
    tilt = report_data.get("regime_factor_tilt", "")
    if not regime:
        return ""
    return f"""<section class="section">
  <h2>Market Regime Context</h2>
  <p><strong>Current Regime:</strong> {regime.replace('_', ' ').title()}</p>
  <p><strong>Factor Tilt:</strong> {tilt}</p>
</section>"""


def _build_conflicts_section(conflicts: list) -> str:
    """Build conflicts section if any exist."""
    if not conflicts:
        return ""
    items = ""
    for c in conflicts:
        agents = ", ".join(c.get("agents", []))
        items += f"""<div class="conflict-box">
      <div class="conflict-agents">{agents}</div>
      <p>{c.get('description', '')}</p>
      <p><em>Resolution: {c.get('resolution', '')}</em></p>
    </div>"""
    return f"""<section class="section">
  <h2>Signal Conflicts</h2>
  {items}
</section>"""


def _build_source_section(report_data: dict) -> str:
    """Build Source Citations section."""
    sources = report_data.get("data_sources", [])
    if not sources:
        return ""
    items = ''.join(f'<li>{s}</li>' for s in sources)
    return f"""<section class="section">
  <h2>Source Citations</h2>
  <ul>{items}</ul>
</section>"""


def _fmt_pct(value: float | None) -> str:
    """Format a percentage value."""
    if value is None:
        return "N/A"
    return f"{value:.1%}"


def _fmt_num(value: float | None) -> str:
    """Format a numeric value."""
    if value is None:
        return "N/A"
    return f"{value:.2f}"
